/*  =========================================================================
    guessten - Represents a Book

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

#ifndef GUESSTEN_H_INCLUDED
#define GUESSTEN_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  Include the library file with typdefs, public includes and public constants
#include "guessten_library.h"


//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT!
//  @warning Please edit the model at "api/guessten.xml" to make changes.
//  @interface
//  Create a new guessten.
GUESSTEN_EXPORT guessten_t *
    guessten_new ();

//  Destroy the guessten.
GUESSTEN_EXPORT void
    guessten_destroy (guessten_t **self_p);

//  
GUESSTEN_EXPORT void
    guessten_play (guessten_t *self);

//  Print properties of the guessten object.
GUESSTEN_EXPORT void
    guessten_print (guessten_t *self);

//  Self test of this class.
GUESSTEN_EXPORT void
    guessten_test (bool verbose);
//  @end

#ifdef __cplusplus
}
#endif

#endif
